apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: angular
  labels:
    app: angular
  annotations:
    openshift.io/generated-by: OpenShiftWebConsole
spec:
  output:
    to:
      kind: ImageStreamTag
      name: angular:latest
  runPolicy: Serial
  source:
    git:
      ref: main
      uri: https://github.com/nerdingitout/serverless-sentiment
    type: Git
    contextDir: "frontend"
  strategy:
    dockerStrategy:
    type: Docker
  triggers:
    - imageChange:
      type: ImageChange
    - type: ConfigChange
    - generic:
        secret: dfgvbh
      type: Generic
    - github:
        secret: dfgvbh
      type: GitHub